name: Release to PyPI (Trusted Publisher)

on:
  # Publish when pushing a version tag, e.g. v0.2.1
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write  # Required for OIDC with PyPI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution
        run: python -m build

      - name: Validate package with Twine
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          # If you set a specific environment in PyPI,
          # uncomment the following line and match it:
          # environment: pypi
